version: "3.9"
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: cm_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: cm_meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili:/meili_data

  backend:
    build:
      context: ./backend
    container_name: cm_backend
    env_file: .env
    depends_on:
      - postgres
      - meilisearch
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  pgdata:
  meili:
